spring:
  datasource:
    url: jdbc:mysql://192.168.1.133:3306/oauth2?useUnicode=true&characterEncoding=UTF8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 192.168.1.133
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9090
resource:
  id: resource
  user-info-uri:
  prefer-token-info: false
